# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from tests.test_helper import TestHelper
from tests.http_response_catcher import HttpResponseCatcher
from plastiqpublicapi.api_helper import APIHelper
from plastiqpublicapi.controllers.recipients_controller import RecipientsController


class RecipientsControllerTests(ControllerTestBase):

    @classmethod
    def setUpClass(cls):
        super(RecipientsControllerTests, cls).setUpClass()
        cls.response_catcher = HttpResponseCatcher()
        cls.controller = RecipientsController(cls.config, cls.response_catcher)

    # Retrieve a paginated list of Recipients by query parameter(s)
    def test_retrieve_a_paginated_list_of_recipients_by_query_parameter_s(self):
        # Parameters for the API call
        payer_id = None
        offset = None
        limit = None

        # Perform the API call through the SDK function
        result = self.controller.retrieve_a_paginated_list_of_recipients_by_query_parameter_s(payer_id, offset, limit)

        # Test response code
        self.assertEquals(self.response_catcher.response.status_code, 200)

        # Test headers
        expected_headers = {}
        expected_headers['trace-id'] = None
        expected_headers['content-type'] = 'application/json'

        self.assertTrue(TestHelper.match_headers(expected_headers, self.response_catcher.response.headers))


