# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from plastiqpublicapi.api_helper import APIHelper
import plastiqpublicapi.exceptions.api_exception
from plastiqpublicapi.models.error_1 import Error1


class ErrorException(plastiqpublicapi.exceptions.api_exception.APIException):
    def __init__(self, reason, response):
        """Constructor for the ErrorException class

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populates the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.code = dictionary.get('code')
        self.message = dictionary.get('message')
        self.errors = None
        if dictionary.get('errors') is not None:
            self.errors = [Error1.from_dictionary(x) for x in dictionary.get('errors')]
        self.trace_id = dictionary.get('traceId')
