# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AccountTypeEnum(object):

    """Implementation of the 'AccountType' enum.

    The type of the bank account

    Attributes:
        CHECKING: TODO: type description here.
        SAVINGS: TODO: type description here.

    """

    CHECKING = 'CHECKING'

    SAVINGS = 'SAVINGS'
