# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Amount(object):

    """Implementation of the 'Amount' model.

    TODO: type model description here.

    Attributes:
        value (float): Value of the currency between 1 and 99999999.99
        currency (string): Currency value

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "value": 'value',
        "currency": 'currency'
    }

    def __init__(self,
                 value=None,
                 currency='USD'):
        """Constructor for the Amount class"""

        # Initialize members of the class
        self.value = value
        self.currency = currency

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        value = dictionary.get('value')
        currency = dictionary.get("currency") if dictionary.get("currency") else 'USD'

        # Return an object of this model
        return cls(value,
                   currency)
