# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from plastiqpublicapi.models.address import Address


class BankAccountResponse(object):

    """Implementation of the 'BankAccountResponse' model.

    TODO: type model description here.

    Attributes:
        account_type (AccountTypeEnum): The type of the bank account
        account_holder_name (string): The legal name of the account holder
        created_at (string): TODO: type description here.
        account_last_four (string): Last 4 digits of the account number
        routing_number (string): The routing number of the bank account
        billing_address (Address): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_type": 'accountType',
        "account_holder_name": 'accountHolderName',
        "created_at": 'createdAt',
        "account_last_four": 'accountLastFour',
        "routing_number": 'routingNumber',
        "billing_address": 'billingAddress'
    }

    def __init__(self,
                 account_type=None,
                 account_holder_name=None,
                 created_at=None,
                 account_last_four=None,
                 routing_number=None,
                 billing_address=None):
        """Constructor for the BankAccountResponse class"""

        # Initialize members of the class
        self.account_type = account_type
        self.account_holder_name = account_holder_name
        self.created_at = created_at
        self.account_last_four = account_last_four
        self.routing_number = routing_number
        self.billing_address = billing_address

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        account_type = dictionary.get('accountType')
        account_holder_name = dictionary.get('accountHolderName')
        created_at = dictionary.get('createdAt')
        account_last_four = dictionary.get('accountLastFour')
        routing_number = dictionary.get('routingNumber')
        billing_address = Address.from_dictionary(dictionary.get('billingAddress')) if dictionary.get('billingAddress') else None

        # Return an object of this model
        return cls(account_type,
                   account_holder_name,
                   created_at,
                   account_last_four,
                   routing_number,
                   billing_address)
