# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from plastiqpublicapi.models.address import Address


class BankAccount(object):

    """Implementation of the 'BankAccount' model.

    Bank Account Funded

    Attributes:
        account_holder_name (string): The legal name of the account holder
        account_number (string): The account number of the bank account
        account_type (AccountTypeEnum): The type of the bank account
        routing_number (string): The routing number of the bank account
        billing_address (Address): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_holder_name": 'accountHolderName',
        "account_number": 'accountNumber',
        "routing_number": 'routingNumber',
        "billing_address": 'billingAddress',
        "account_type": 'accountType'
    }

    def __init__(self,
                 account_holder_name=None,
                 account_number=None,
                 routing_number=None,
                 billing_address=None,
                 account_type=None):
        """Constructor for the BankAccount class"""

        # Initialize members of the class
        self.account_holder_name = account_holder_name
        self.account_number = account_number
        self.account_type = account_type
        self.routing_number = routing_number
        self.billing_address = billing_address

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        account_holder_name = dictionary.get('accountHolderName')
        account_number = dictionary.get('accountNumber')
        routing_number = dictionary.get('routingNumber')
        billing_address = Address.from_dictionary(dictionary.get('billingAddress')) if dictionary.get('billingAddress') else None
        account_type = dictionary.get('accountType')

        # Return an object of this model
        return cls(account_holder_name,
                   account_number,
                   routing_number,
                   billing_address,
                   account_type)
