# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Category(object):

    """Implementation of the 'Category' model.

    TODO: type model description here.

    Attributes:
        id (uuid|string): TODO: type description here.
        display_name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "display_name": 'displayName'
    }

    def __init__(self,
                 id=None,
                 display_name=None):
        """Constructor for the Category class"""

        # Initialize members of the class
        self.id = id
        self.display_name = display_name

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        display_name = dictionary.get('displayName')

        # Return an object of this model
        return cls(id,
                   display_name)
