# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClientSecretsResponse(object):

    """Implementation of the 'Client Secrets Response' model.

    TODO: type model description here.

    Attributes:
        client_secret (string): Client Secret returned by /client-secrets

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "client_secret": 'clientSecret'
    }

    def __init__(self,
                 client_secret=None):
        """Constructor for the ClientSecretsResponse class"""

        # Initialize members of the class
        self.client_secret = client_secret

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        client_secret = dictionary.get('clientSecret')

        # Return an object of this model
        return cls(client_secret)
