# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from plastiqpublicapi.models.payer_id import PayerId


class ClientSecretsRequest(object):

    """Implementation of the 'Client Secrets Request' model.

    TODO: type model description here.

    Attributes:
        payer (PayerId): TODO: type description here.
        mtype (Type7Enum): The type of object to create the Client Secret for.
            Defaults to CARD.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payer": 'payer',
        "mtype": 'type'
    }

    def __init__(self,
                 payer=None,
                 mtype=None):
        """Constructor for the ClientSecretsRequest class"""

        # Initialize members of the class
        self.payer = payer
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        payer = PayerId.from_dictionary(dictionary.get('payer')) if dictionary.get('payer') else None
        mtype = dictionary.get('type')

        # Return an object of this model
        return cls(payer,
                   mtype)
