# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from plastiqpublicapi.models.payer_id import PayerId


class CreatePaymentRequestFromId(object):

    """Implementation of the 'CreatePaymentRequestFromId' model.

    TODO: type model description here.

    Attributes:
        payment_intent (object): TODO: type description here.
        payer (PayerId): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payment_intent": 'paymentIntent',
        "payer": 'payer'
    }

    def __init__(self,
                 payment_intent=None,
                 payer=None):
        """Constructor for the CreatePaymentRequestFromId class"""

        # Initialize members of the class
        self.payment_intent = payment_intent
        self.payer = payer

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        payment_intent = dictionary.get('paymentIntent')
        payer = PayerId.from_dictionary(dictionary.get('payer')) if dictionary.get('payer') else None

        # Return an object of this model
        return cls(payment_intent,
                   payer)
