# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Error1(object):

    """Implementation of the 'Error1' model.

    TODO: type model description here.

    Attributes:
        details (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "details": 'details'
    }

    def __init__(self,
                 details=None):
        """Constructor for the Error1 class"""

        # Initialize members of the class
        self.details = details

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        details = dictionary.get('details')

        # Return an object of this model
        return cls(details)
