# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FileTypeEnum(object):

    """Implementation of the 'FileType' enum.

    TODO: type enum description here.

    Attributes:
        DOC: TODO: type description here.
        DOCX: TODO: type description here.
        GIF: TODO: type description here.
        JPEG: TODO: type description here.
        JPG: TODO: type description here.
        PDF: TODO: type description here.
        XLS: TODO: type description here.
        XLSX: TODO: type description here.

    """

    DOC = 'doc'

    DOCX = 'docx'

    GIF = 'gif'

    JPEG = 'jpeg'

    JPG = 'jpg'

    PDF = 'pdf'

    XLS = 'xls'

    XLSX = 'xlsx'
