# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IdentityDocumentResponse(object):

    """Implementation of the 'IdentityDocumentResponse' model.

    TODO: type model description here.

    Attributes:
        mtype (Type5Enum): TODO: type description here.
        id (uuid|string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": 'type',
        "id": 'id'
    }

    def __init__(self,
                 mtype=None,
                 id=None):
        """Constructor for the IdentityDocumentResponse class"""

        # Initialize members of the class
        self.mtype = mtype
        self.id = id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get('type')
        id = dictionary.get('id')

        # Return an object of this model
        return cls(mtype,
                   id)
