# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from plastiqpublicapi.models.address import Address


class PatchCard(object):

    """Implementation of the 'PatchCard' model.

    Debit or Credit Card

    Attributes:
        card_holder_name (string): TODO: type description here.
        cvv (string): 3-4 digits
        expiration_month (string): TODO: type description here.
        expiration_year (string): TODO: type description here.
        billing_address (Address): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "cvv": 'cvv',
        "card_holder_name": 'cardHolderName',
        "expiration_month": 'expirationMonth',
        "expiration_year": 'expirationYear',
        "billing_address": 'billingAddress'
    }

    def __init__(self,
                 cvv=None,
                 card_holder_name=None,
                 expiration_month=None,
                 expiration_year=None,
                 billing_address=None):
        """Constructor for the PatchCard class"""

        # Initialize members of the class
        self.card_holder_name = card_holder_name
        self.cvv = cvv
        self.expiration_month = expiration_month
        self.expiration_year = expiration_year
        self.billing_address = billing_address

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        cvv = dictionary.get('cvv')
        card_holder_name = dictionary.get('cardHolderName')
        expiration_month = dictionary.get('expirationMonth')
        expiration_year = dictionary.get('expirationYear')
        billing_address = Address.from_dictionary(dictionary.get('billingAddress')) if dictionary.get('billingAddress') else None

        # Return an object of this model
        return cls(cvv,
                   card_holder_name,
                   expiration_month,
                   expiration_year,
                   billing_address)
