# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from plastiqpublicapi.api_helper import APIHelper
from plastiqpublicapi.models.address import Address
from plastiqpublicapi.models.identity_document_response import IdentityDocumentResponse


class Payer(object):

    """Implementation of the 'Payer' model.

    TODO: type model description here.

    Attributes:
        id (uuid|string): TODO: type description here.
        business_name (string): TODO: type description here.
        contact (object): TODO: type description here.
        business_address (Address): TODO: type description here.
        created_at (datetime): TODO: type description here.
        status (StatusEnum): TODO: type description here.
        identity_documents (list of IdentityDocumentResponse): TODO: type
            description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "business_name": 'businessName',
        "contact": 'contact',
        "business_address": 'businessAddress',
        "created_at": 'createdAt',
        "status": 'status',
        "identity_documents": 'identityDocuments'
    }

    def __init__(self,
                 id=None,
                 business_name=None,
                 contact=None,
                 business_address=None,
                 created_at=None,
                 status=None,
                 identity_documents=None):
        """Constructor for the Payer class"""

        # Initialize members of the class
        self.id = id
        self.business_name = business_name
        self.contact = contact
        self.business_address = business_address
        self.created_at = APIHelper.RFC3339DateTime(created_at) if created_at else None
        self.status = status
        self.identity_documents = identity_documents

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        business_name = dictionary.get('businessName')
        contact = dictionary.get('contact')
        business_address = Address.from_dictionary(dictionary.get('businessAddress')) if dictionary.get('businessAddress') else None
        created_at = APIHelper.RFC3339DateTime.from_value(dictionary.get("createdAt")).datetime if dictionary.get("createdAt") else None
        status = dictionary.get('status')
        identity_documents = None
        if dictionary.get('identityDocuments') is not None:
            identity_documents = [IdentityDocumentResponse.from_dictionary(x) for x in dictionary.get('identityDocuments')]

        # Return an object of this model
        return cls(id,
                   business_name,
                   contact,
                   business_address,
                   created_at,
                   status,
                   identity_documents)
