# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentStatusEnum(object):

    """Implementation of the 'PaymentStatus' enum.

    The current state of a Payment

    Attributes:
        SUBMITTED: TODO: type description here.
        COMMITTED: TODO: type description here.
        DEPOSITED: TODO: type description here.
        CANCELLED: TODO: type description here.

    """

    SUBMITTED = 'SUBMITTED'

    COMMITTED = 'COMMITTED'

    DEPOSITED = 'DEPOSITED'

    CANCELLED = 'CANCELLED'
