# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentMethodStatusEnum(object):

    """Implementation of the 'PaymentMethodStatus' enum.

    In some cases Payment Method will remain Inactive until additional
    information provided

    Attributes:
        ACTIVE: TODO: type description here.
        INACTIVE: TODO: type description here.

    """

    ACTIVE = 'ACTIVE'

    INACTIVE = 'INACTIVE'
