# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PaymentRefundRequest(object):

    """Implementation of the 'PaymentRefundRequest' model.

    TODO: type model description here.

    Attributes:
        payer_id (uuid|string): The ID of the Payer the Payment to refund
            belongs to

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "payer_id": 'payerId'
    }

    def __init__(self,
                 payer_id=None):
        """Constructor for the PaymentRefundRequest class"""

        # Initialize members of the class
        self.payer_id = payer_id

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        payer_id = dictionary.get('payerId')

        # Return an object of this model
        return cls(payer_id)
