# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status3Enum(object):

    """Implementation of the 'Status3' enum.

    TODO: type enum description here.

    Attributes:
        CAPTURABLE: TODO: type description here.
        CAPTURED: TODO: type description here.
        EXPIRED: TODO: type description here.
        UNCAPTURABLE: TODO: type description here.

    """

    CAPTURABLE = 'CAPTURABLE'

    CAPTURED = 'CAPTURED'

    EXPIRED = 'EXPIRED'

    UNCAPTURABLE = 'UNCAPTURABLE'
