# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusEnum(object):

    """Implementation of the 'Status' enum.

    The status of an object

    Attributes:
        ACTIVE: TODO: type description here.
        INACTIVE: TODO: type description here.
        UNKNOWN: TODO: type description here.

    """

    ACTIVE = 'ACTIVE'

    INACTIVE = 'INACTIVE'

    UNKNOWN = 'UNKNOWN'
