# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status1Enum(object):

    """Implementation of the 'Status1' enum.

    Representation of whether the Payment was successfully refunded or not

    Attributes:
        REFUNDED: TODO: type description here.
        REFUND_FAILED: TODO: type description here.

    """

    REFUNDED = 'REFUNDED'

    REFUND_FAILED = 'REFUND_FAILED'
