# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class SubTypeEnum(object):

    """Implementation of the 'SubType' enum.

    TODO: type enum description here.

    Attributes:
        CREDIT: TODO: type description here.
        DEBIT: TODO: type description here.

    """

    CREDIT = 'CREDIT'

    DEBIT = 'DEBIT'
