# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type2Enum(object):

    """Implementation of the 'Type2' enum.

    TODO: type enum description here.

    Attributes:
        CARD: TODO: type description here.
        BANK_ACCOUNT: TODO: type description here.

    """

    CARD = 'CARD'

    BANK_ACCOUNT = 'BANK_ACCOUNT'
