# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type5Enum(object):

    """Implementation of the 'Type5' enum.

    TODO: type enum description here.

    Attributes:
        US_TIN: TODO: type description here.
        US_EIN: TODO: type description here.
        US_SSN: TODO: type description here.
        PASSPORT_NUMBER: TODO: type description here.
        ALIEN_REGISTRATION_NUMBER: TODO: type description here.

    """

    US_TIN = 'US_TIN'

    US_EIN = 'US_EIN'

    US_SSN = 'US_SSN'

    PASSPORT_NUMBER = 'PASSPORT_NUMBER'

    ALIEN_REGISTRATION_NUMBER = 'ALIEN_REGISTRATION_NUMBER'
