# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TypeEnum(object):

    """Implementation of the 'Type' enum.

    The type of fee applied to the payment

    Attributes:
        PLASTIQ_SERVICE_FEE: TODO: type description here.
        PLASTIQ_CROSS_BORDER_FEE: TODO: type description here.

    """

    PLASTIQ_SERVICE_FEE = 'PLASTIQ_SERVICE_FEE'

    PLASTIQ_CROSS_BORDER_FEE = 'PLASTIQ_CROSS_BORDER_FEE'
