# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Type7Enum(object):

    """Implementation of the 'Type7' enum.

    The type of object to create the Client Secret for. Defaults to CARD.

    Attributes:
        CARD: TODO: type description here.

    """

    CARD = 'CARD'
