# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Wire(object):

    """Implementation of the 'Wire' model.

    TODO: type model description here.

    Attributes:
        mtype (string): TODO: type description here.
        account_number (string): Bank wire account number (alphanumeric)
        routing_number (string): Bank wire routing number
        beneficiary_name (string): TODO: type description here.
        country (string): Two-letter country code (ISO 3166-1 alpha-2).

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mtype": 'type',
        "account_number": 'accountNumber',
        "routing_number": 'routingNumber',
        "beneficiary_name": 'beneficiaryName',
        "country": 'country'
    }

    def __init__(self,
                 mtype='WIRE',
                 account_number=None,
                 routing_number=None,
                 beneficiary_name=None,
                 country='US'):
        """Constructor for the Wire class"""

        # Initialize members of the class
        self.mtype = mtype
        self.account_number = account_number
        self.routing_number = routing_number
        self.beneficiary_name = beneficiary_name
        self.country = country

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        mtype = dictionary.get("type") if dictionary.get("type") else 'WIRE'
        account_number = dictionary.get('accountNumber')
        routing_number = dictionary.get('routingNumber')
        beneficiary_name = dictionary.get('beneficiaryName')
        country = dictionary.get("country") if dictionary.get("country") else 'US'

        # Return an object of this model
        return cls(mtype,
                   account_number,
                   routing_number,
                   beneficiary_name,
                   country)
