# -*- coding: utf-8 -*-

"""
plastiqpublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from plastiqpublicapi.api_helper import APIHelper
from plastiqpublicapi.configuration import Server
from plastiqpublicapi.controllers.base_controller import BaseController
from plastiqpublicapi.http.auth.o_auth_2 import OAuth2
from plastiqpublicapi.models.client_secrets_response import ClientSecretsResponse
from plastiqpublicapi.exceptions.error_exception import ErrorException


class ClientSecretsController(BaseController):

    """A Controller to access Endpoints in the plastiqpublicapi API."""

    def __init__(self, config, call_back=None):
        super(ClientSecretsController, self).__init__(config, call_back)

    def create_a_single_use_client_secret(self,
                                          body,
                                          trace_id=None,
                                          user_agent=None,
                                          end_user_device_id=None,
                                          end_user_ip=None):
        """Does a POST request to /client-secrets.

        Create a single-use Client Secret

        Args:
            body (ClientSecretsRequest): Create a single-use Client Secret to
                be shared with browser for tokenization of sensitive data such
                as credit card numbers. The Client Secret expires after 60
                seconds.
            trace_id (string, optional): A valid UUID (V4) for tracing
                requests. Will be returned as a header. If not present or
                invalid, a generated UUID will be returned.
            user_agent (string, optional): A string representing the User
                Agent. Required only when the request is not coming from the
                end user's browser.
            end_user_device_id (string, optional): A unique identifier for the
                end user's browser. Recommended for compliance when the
                request is not coming from the end user's browser.
            end_user_ip (string, optional): The IP address of the end user.
                Recommended for compliance when the request is not coming from
                the end user's browser.

        Returns:
            ClientSecretsResponse: Response from the API. Client Secret
                created successfully

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """

        # Prepare query URL
        _url_path = '/client-secrets'
        _query_builder = self.config.get_base_uri()
        _query_builder += _url_path
        _query_url = APIHelper.clean_url(_query_builder)

        # Prepare headers
        _headers = {
            'accept': 'application/json',
            'content-type': 'application/json; charset=utf-8',
            'Trace-Id': trace_id,
            'User-Agent': user_agent,
            'End-User-Device-Id': end_user_device_id,
            'End-User-Ip': end_user_ip
        }

        # Prepare and execute request
        _request = self.config.http_client.post(_query_url, headers=_headers, parameters=APIHelper.json_serialize(body))
        OAuth2.apply(self.config, _request)
        _response = self.execute_request(_request)

        # Endpoint and global error handling using HTTP status codes.
        if _response.status_code == 400:
            raise ErrorException('Bad Request', _response)
        elif _response.status_code == 401:
            raise ErrorException('Unauthorized', _response)
        elif _response.status_code == 403:
            raise ErrorException('Forbidden', _response)
        elif _response.status_code == 500:
            raise ErrorException('Internal Server Error', _response)
        self.validate_response(_response)

        decoded = APIHelper.json_deserialize(_response.text, ClientSecretsResponse.from_dictionary)

        return decoded
